# Generated by Django 4.2 on 2023-04-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyanalytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null = True,default=None, upload_to='images/'),
            preserve_default=False
        ),
    ]
