# Generated by Django 4.2 on 2023-04-27 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyanalytics', '0005_alter_post_content_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='plot_data',
        ),
    ]
