# Generated by Django 4.2 on 2023-04-27 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easyanalytics', '0009_auto_20230427_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='plot_data',
        ),
    ]
