# Generated by Django 4.2 on 2023-04-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easyanalytics', '0010_remove_post_plot_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
